Request code review to merge feature to dev
fedgut/mv-ruby-02-enumerate pull request #1
Opened 2019-10-04 20:32 UTC by fedgut

Request code review to merge enumerate methods feature to dev

2019-10-05 01:16 UTC, Ispirett requested changes
Hey! @fedgut  great work so far :+1:  :100:  there are just some bugs :bug: to address below.

submit for review when done.

2019-10-05 01:16 UTC, Ispirett commented on scripts/enumerate.rb
> +
**These methods** should have a parameter.
without it I'm getting an ArgumentError: wrong number of arguments (given 1, expected 0)
should be able to handle when a block is not given.

2019-10-05 01:16 UTC, Ispirett commented on scripts/enumerate.rb
> +  def my_inject(init = nil)
**My_inject** should be able to handle when a block is not given.
When testing with
  undefined local variable or method `length' for 5..50:Range

2019-10-05 01:16 UTC, Ispirett commented on scripts/enumerate.rb
> +  end
**These methods**
should be able to handle when a block is not given.

2019-10-15 04:56 UTC, Oghenebrume50 requested changes
Hi @fedgut good Job :smile: there are just very few changes left to get this project approved, I left the comments on them. 
Please make changes and request another review. 
**[IMPORTANT]** It has been noticed that you and your partner aren't following the curriculum order in the sense that you are currently working on a project later down the line after this, please this is not ideal, the curriculum was created as a guide,  it is adviced to take this one step at a time, you guys will benefit more this way. :+1:

2019-10-15 04:56 UTC, Oghenebrume50 commented on lib/enum.rb
> +  def my_all?(pattern = nil)
Should work with classes passed as arguments.  And work with regular pattern too

2019-10-15 04:56 UTC, Oghenebrume50 commented on lib/enum.rb
> +  def my_any?(pattern = nil)
Should work with classes passed as arguments.  And work with regular pattern too

2019-10-15 04:56 UTC, Oghenebrume50 commented on lib/enum.rb
> +  def my_none?(pattern = nil)
Should work with classes passed as arguments.  And work with regular pattern too

2019-10-16 15:53 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: . However, some of your methods are not satisfying the requirements. check :arrow_down: 

- Check the code comments below :arrow_down: 

### That's it. When finished, kindly resubmit another code review form :pray: 

##### Ahmed Mahfoudh TSE

2019-10-16 15:53 UTC, stratospherique commented on lib/enum.rb
> +  end
* [x] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-10-16 15:53 UTC, stratospherique commented on lib/enum.rb
> +  end
* [x] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-10-16 15:53 UTC, stratospherique commented on lib/enum.rb
> +  end
* [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-10-16 19:39 UTC, whiz25 approved these changes
## Awesome :clap: 
You have made the requested changes and therefore it's a :+1:  from me. Please merge and proceed.

#### Martin Afani

2019-10-16 19:46 UTC, merged